---
abstract: 'it seems sweet, but it probably has long-term adverse health effects'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.006, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Aspartame
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  MooX::Aspartame:
    file: lib/MooX/Aspartame.pm
    version: 0.005
  MooX::Aspartame::CodeGenerator:
    file: lib/MooX/Aspartame/CodeGenerator.pm
    version: 0.005
  MooX::Aspartame::CodeGenerator::Class:
    file: lib/MooX/Aspartame/CodeGenerator/Class.pm
    version: 0.005
  MooX::Aspartame::CodeGenerator::Role:
    file: lib/MooX/Aspartame/CodeGenerator/Role.pm
    version: 0.005
  MooX::Aspartame::DefineKeyword:
    file: lib/MooX/Aspartame/DefineKeyword.pm
    version: 0.005
  MooX::Aspartame::ImportSet:
    file: lib/MooX/Aspartame/ImportSet.pm
    version: 0.005
  MooX::Aspartame::MethodModifiers:
    file: lib/MooX/Aspartame/MethodModifiers.pm
    version: 0.005
  MooX::Aspartame::Parser:
    file: lib/MooX/Aspartame/Parser.pm
    version: 0.005
requires:
  Devel::Pragma: 0.54
  Exporter::TypeTiny: 0.022
  Function::Parameters: 1.0201
  Import::Into: 1.000000
  Keyword::Simple: 0.01
  Module::Runtime: 0.013
  Moo: 1.003000
  MooX::late: 0.014
  Scalar::Util: 1.24
  Try::Tiny: 0.12
  Type::Utils: 0.022
  namespace::sweep: 0.006
  true: 0.18
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooX-Aspartame/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-Aspartame
  homepage: https://metacpan.org/release/MooX-Aspartame
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moox-aspartame
version: 0.005
x_provides_scripts: {}
